---
title: "Resume"
---
###
## JOSEPHINE M. ALFORD

204 Sandy Springs Drive, Rincon, GA 31326 
(912) 547-7034 
josiealford14@gmail.com
jma2249@columbia.edu 

### EDUCATION
Columbia University Mailman School of Public Health, New York, New York
Master of Science in Biostatistics, Anticipated May 2019

Emory University, Atlanta, GA	  
Bachelor of Arts in Economics, May 2017                                                              
Bachelor of Arts in Sociology, May 2017
Cumulative GPA: 3.45

### EXPERIENCE
* Emory University Office of Equity and Inclusion
Access, Disability Services and Resources (ADSR)

    * Volunteer Notetaker, August 2016-May 2017, Atlanta, GA

     * Provided detailed and accurate lecture notes for students with disabilities for Econometrics, Social Research and Health Policy courses.
    
* Project SHINE (Students Helping in Naturalization and English), 
Catholic Charities of Atlanta, Center for Pan Asian Community Services & Fugees Family

    * Volunteer ESL Teacher Assistant & Tutor, January 2015-May 2017 Chamblee, GA
  
      * Taught English language to immigrants and refugees.  
    
      * Conducted one-on-one tutoring to assist students with enunciation, spelling, diction, and vocabulary.
    
* Emory Reads

    * Teacher Assistant & Tutor, August 2014-May 2017, Atlanta, GA
  
      * Tutored elementary and middle school students of the Atlanta Public Schools to develop reading comprehension skills in preparation for state standardized tests.
    
      * Served as mentor to economically disadvantaged and minority students, advising on future academic paths and encouraging interpersonal skills. 
    
* The Ben Franklin Academy 

    * Teacher Assistant Intern, August 2016-December 2016, Atlanta, GA
      
      * Assisted the Head of School with administrative tasks such as academic scheduling and lessons plans.
   
      * Tutored high school students with learning disabilities with English assignments for AP English Literature, AP English Language and 10th Grade English.  

* Emory Winship Cancer Institute Genetics Department and Infusion Center

    * Hospitality & Clerical/Administrative Volunteer, August 2014-May 2015, Atlanta, GA

        * Assisted genetic counselors and other health care professionals with medical records and insurance forms, performed administrative duties, and worked with staff liaisons to provide quality patient care. 
      
        * Greeted incoming patients, conducted intake activities, and performed patient rounding duties, and provided customer service by addressing questions and concerns.

* Student Alliance for Health Involvement (SAHI)

    * Publicity Chair & Committee Member, August 2013-May 2015, Atlanta, GA
    
      * Publicized general body meetings, community health fairs, and other events using social media and printed advertisements.
      
      * Promoted health among the Greater Atlanta immigrant community and collected feedback.
      
      * Maintained records of organizational contributions and documented events by taking pictures.

* Medshare Medical Relief

    * Volunteer, January 2014-March 2015, Decatur, GA
   
      * Prepared surplus medical supplies for shipping to economically disadvantaged communities.

### RELEVANT COURSEWORK
Data Science I, Biostatistical Methods, Probability, Principles of Epidemiology, Economic Forecasting, Microeconometrics, Econometrics, Health Economics, Social Research, Probability & Statistics for Economists, Linear Algebra, Multivariable (Advanced) Calculus, Calculus II, Calculus I, Computer Science I, Statistical Inference, Epidemiology, General Chemistry I & II, Physics I, Organic Chemistry I, General Biology I & II, Health Policy

### MEMBERSHIP
The American Statistical Association
Biostatistical Student Cohort

### COMPUTER SKILLS
Stata, R, SAS, Microsoft Word, Excel, Outlook, and PowerPoint